version: "3.8"

services:
  frontend:
    restart: on-failure
    container_name: DynamoDashboard
    build: ./client
    ports:
      - "4545:4545"
    networks:
      - node_network

  backend:
    restart: on-failure
    build: ./server
    container_name: DynamoNode
    ports:
      - "7000:7000"
    networks:
      - node_network

  # proxy:
  #   restart: unless-stopped
  #   container_name: DynamoProxy
  #   image: nginx
  #   ports:
  #     - ${NGINX_PORT}:${NGINX_PORT}
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - node_network

networks:
  node_network:
