version: "3.8"

services:
  backend:
    restart: on-failure
    build: ./server
    container_name: DynamoNode
    ports:
      - "7000:7000"
    networks:
      - node_network

  frontend:
    restart: on-failure
    container_name: DynamoProxy
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    networks:
      - node_network

networks:
  node_network:
