version: "3.8"

services:
  backend:
    restart: always
    build: ./server
    container_name: DynamoNode
    ports:
      - "7000:7000"
    networks:
      - node_network

  frontend:
    restart: always
    container_name: DynamoDashboard
    build: ./client
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - node_network

  # proxy:
  #   restart: unless-stopped
  #   container_name: DynamoProxy
  #   image: nginx
  #   ports:
  #     - ${NGINX_PORT}:${NGINX_PORT}
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - node_network

networks:
  node_network:
