version: "3.8"

services:
  backend:
    restart: on-failure
    build: ./server
    ports:
      - "7000:7000"
  frontend:
    restart: on-failure
    build: ./client
    ports:
      - "3000:3000"
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network:
