[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$or03UMXb$YUZhwxixCCq2e/hKYZtAq."
  ]

[http.routers.api]
  rule = "Host(`monitor.jubot.site`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
